services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5434:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movemates
  web:
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - 8086:8086
    expose:
      - 8086
    environment:
      - postgresql_host=postgres
      - postgresql_db=movemates
      - ACCESS_CONTROL_ALLOW_ORIGING=localhost:8086