name: move_mates_android
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-397.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #presentation layer
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  intl_phone_field: ^3.1.0
  email_validator: ^2.1.17
  easy_splash_screen: ^1.0.4

  #to compare models
  equatable: ^2.0.5
  #state management
  flutter_bloc: ^8.1.3
  #local cache
  flutter_secure_storage: ^8.0.0
  #service locator
  get_it: ^7.6.0
  #functional programming thingies
  dartz: ^0.10.1
  #to check internet connection
  internet_connection_checker: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/icons/auth/
    - assets/icons/user/

